apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

images:
- name: zwensman/simple-app
  newName: zwensman/simple-app
  newTag: v0.1.0
commonAnnotations:
  version: v0.1.0

resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
