on:
  push:
    tags:
      - "*"

env:
  IMAGE: zwensman/simple-app
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.8.0

      - id: docker-login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: pack-build
        working-directory: app
        run: |
          pack build ${IMAGE}:${GITHUB_REF_NAME} \
              --builder paketobuildpacks/builder:base \
              --buildpack paketo-buildpacks/python \
              --publish

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - uses: imranismail/setup-kustomize@v1

      - id: bump-manifest-tag
        working-directory: app/manifests
        run: |
          kustomize edit set image ${IMAGE}=${IMAGE}:${GITHUB_REF_NAME}
          kustomize edit set annotation version:${GITHUB_REF_NAME}
          git config user.email "m.zwennes@felyx.com"
          git config user.name "Martijn Zwennes"
          git add .
          git commit -m "Bump ${IMAGE} to ${GITHUB_REF_NAME}"
          git push origin HEAD:main

      - id: aws-login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: kubectl-apply
        uses: kodermax/kubectl-aws-eks@1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -k app/manifests
